// Torque Input Map File
if (isObject(MoveMap)) MoveMap.delete();
new ActionMap(MoveMap);
MoveMap.bindCmd(keyboard, "escape", "", "escapeFromGame();");
MoveMap.bind(keyboard, "f2", showPlayerList);
MoveMap.bind(keyboard, "f5", toggleParticleEditor);
MoveMap.bind(keyboard, "a", moveleft);
MoveMap.bind(keyboard, "d", moveright);
MoveMap.bind(keyboard, "w", moveforward);
MoveMap.bind(keyboard, "s", movebackward);
MoveMap.bind(keyboard, "space", jump);
MoveMap.bind(keyboard, "r", setZoomFOV);
MoveMap.bind(keyboard, "e", toggleZoom);
MoveMap.bind(keyboard, "z", toggleFreeLook);
MoveMap.bind(keyboard, "tab", toggleFirstPerson);
MoveMap.bind(keyboard, "alt c", toggleCamera);
MoveMap.bindCmd(keyboard, "ctrl w", "commandToServer(\'playCel\',\"wave\");", "");
MoveMap.bindCmd(keyboard, "ctrl s", "commandToServer(\'playCel\',\"salute\");", "");
MoveMap.bindCmd(keyboard, "ctrl k", "commandToServer(\'suicide\');", "");
MoveMap.bindCmd(keyboard, "h", "commandToServer(\'use\',\"HealthKit\");", "");
MoveMap.bindCmd(keyboard, "1", "commandToServer(\'use\',\"Crossbow\");", "");
MoveMap.bind(keyboard, "u", toggleMessageHud);
MoveMap.bind(keyboard, "pageup", pageMessageHudUp);
MoveMap.bind(keyboard, "pagedown", pageMessageHudDown);
MoveMap.bind(keyboard, "p", resizeMessageHud);
MoveMap.bind(keyboard, "f3", startRecordingDemo);
MoveMap.bind(keyboard, "f4", stopRecordingDemo);
MoveMap.bind(keyboard, "f8", dropCameraAtPlayer);
MoveMap.bind(keyboard, "f7", dropPlayerAtCamera);
MoveMap.bind(keyboard, "ctrl o", bringUpOptions);
MoveMap.bindCmd(keyboard, "n", "NetGraph::toggleNetGraph();", "");
MoveMap.bind(mouse0, "xaxis", yaw);
MoveMap.bind(mouse0, "yaxis", pitch);
MoveMap.bind(mouse0, "button0", mouseFire);
